In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)

In [2]:
import pandas as pd

In [3]:
data = {
    "Roll no" : [1,2,3,4,5],
    "Name" : ["Aarti", "Priya", "Rameshavri", "Shital", "Neha"],
    "Course" : ["DA","DS","Cloud","DA","JAVA"]   
}

df = pd.DataFrame(data)
df

   Roll no        Name Course
0        1       Aarti     DA
1        2       Priya     DS
2        3  Rameshavri  Cloud
3        4      Shital     DA
4        5        Neha   JAVA

# Dataframe Creation

In [4]:
data = {'Name': ['Amit', 'Sara'], 'Age': [20, 22]}
df = pd.DataFrame(data)
print(df)

   Name  Age
0  Amit   20
1  Sara   22

# Series

In [5]:
s = pd.Series([10,20,30])
print(s)

0    10
1    20
2    30
dtype: int64

In [6]:
#custom index
s = pd.Series([10,20,30], index=["a","b","c"])
print(s)

a    10
b    20
c    30
dtype: int64

In [7]:
# from dictionary
data = {"name": "aarti", "age": 22, "course": "DA"}
s = pd.Series(data)
print(s)

name      aarti
age          22
course       DA
dtype: object

In [8]:
#mixed datatypes
datatypes = pd.Series([10,"aarti",22.4])
print(datatypes)

0       10
1    aarti
2     22.4
dtype: object

In [9]:
#missing values

import numpy as np
s = pd.Series([10, np.nan, 20])
print(s)

0    10.0
1     NaN
2    20.0
dtype: float64

In [10]:
#scalar value : Broadcasting 

s = pd.Series(5, index = [0,1,2,3,4,5])
print(s)

0    5
1    5
2    5
3    5
4    5
5    5
dtype: int64

In [11]:
#naming series

s = pd.Series([10,20,30,'w'], name = "Numbers")
print(s)

0    10
1    20
2    30
3     w
Name: Numbers, dtype: object

In [12]:
#Accessing elements

s = pd.Series([10,20,30,40,50])
print(s[2])

30

# Data Inspection Functions

In [13]:
# 1.df.head()
# 2.df.tail()
# 3.df.info()
# 4.df.describe()
# 5.df.shape
# 6.df.dtypes
# 7.df.columns
# 8.df.index

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Name": ['A','B','C','D','E','F','G','H'],
    "Marks" : [50,60,76,78,90,99,87,72],
    "Age": [22,21,19,21,20,18,22,23]
})
print(df)

  Name  Marks  Age
0    A     50   22
1    B     60   21
2    C     76   19
3    D     78   21
4    E     90   20
5    F     99   18
6    G     87   22
7    H     72   23

In [15]:
#1.df.head() : 1st 5
print(df.head())

  Name  Marks  Age
0    A     50   22
1    B     60   21
2    C     76   19
3    D     78   21
4    E     90   20

In [16]:
# 2.df.tail() : last 5
print(df.tail())

  Name  Marks  Age
3    D     78   21
4    E     90   20
5    F     99   18
6    G     87   22
7    H     72   23

In [17]:
# 3.df.info() : full info
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      str
 1   Marks   8 non-null      int64
 2   Age     8 non-null      int64
dtypes: int64(2), str(1)
memory usage: 324.0 bytes
None

In [18]:
# 4.df.describe() : numeric columns's summary (average, min, max, etc.)

print(df.describe())

           Marks        Age
count   8.000000   8.000000
mean   76.500000  20.750000
std    16.017847   1.669046
min    50.000000  18.000000
25%    69.000000  19.750000
50%    77.000000  21.000000
75%    87.750000  22.000000
max    99.000000  23.000000

In [19]:
# 5.df.shape : no of rows and columns 

print(df.shape)

(8, 3)

In [20]:
# 6.df.dtypes  : every column's datatype
print(df.dtypes)

Name       str
Marks    int64
Age      int64
dtype: object

In [21]:
# 7.df.columns
print(df.columns)

Index(['Name', 'Marks', 'Age'], dtype='str')

In [22]:
# 8.df.index : shows row numbering (index)
print(df.index)

RangeIndex(start=0, stop=8, step=1)

# Data Selection Functions

In [23]:
# 9.df['column']
# 10.df[['col1','col2']]
# 11.df.loc[2]
# 12.df.loc[:, 'name']
# 13.df.loc[2:5, ['name','age']]
# 14.df.iloc[2]
# 15.df.iloc[:, 1:3]

import pandas as pd

df = pd.DataFrame({
    "Name": ['A','B','C','D','E','F','G','H'],
    "Marks" : [50,60,76,78,90,99,87,72],
    "Age": [22,21,19,21,20,18,22,23]
})
print(df)

  Name  Marks  Age
0    A     50   22
1    B     60   21
2    C     76   19
3    D     78   21
4    E     90   20
5    F     99   18
6    G     87   22
7    H     72   23

In [24]:
# 9.df['column'] select only one column
print(df['Name'])

0    A
1    B
2    C
3    D
4    E
5    F
6    G
7    H
Name: Name, dtype: str

In [25]:
# 10.df[['col1','col2']]

print(df[['Name','Age']])

  Name  Age
0    A   22
1    B   21
2    C   19
3    D   21
4    E   20
5    F   18
6    G   22
7    H   23

In [26]:
# 11.df.loc[2] : label (index) use karun row select : loc means location 

print(df.loc[2])

Name      C
Marks    76
Age      19
Name: 2, dtype: object

In [27]:
# 12.df.loc[:, 'name'] 
print(df.loc[:, 'Name']) #  ":"=> all rows and specific columns

0    A
1    B
2    C
3    D
4    E
5    F
6    G
7    H
Name: Name, dtype: str

In [28]:
# 13.df.loc[2:5, ['name','age']]  : rows (2 to 5) + specific columns

print(df.loc[2:5,['Name', 'Age']])

  Name  Age
2    C   19
3    D   21
4    E   20
5    F   18

In [29]:
# 14.df.iloc[2] : position (index number) used karun row

print(df.iloc[2])

Name      C
Marks    76
Age      19
Name: 2, dtype: object

In [30]:
#difference between loc and iloc :

print(df.loc[3]) #(label / name used krto)
print(df.iloc[0]) # (position / index used krto )

Name      D
Marks    78
Age      21
Name: 3, dtype: object
Name      A
Marks    50
Age      22
Name: 0, dtype: object

In [31]:
# print(df.iloc[2])
# print(df.loc[2])

# differnece : loc[2] => index ch naav gheto
#            : iloc[2] => index gheto 

# eg;

import pandas as pd

df = pd.DataFrame({
    "Name": ["A","B","C"]}, index = [10,20,30]
)
print(df)

print(df.loc[20]) #name
print(df.iloc[2]) #index

   Name
10    A
20    B
30    C
Name    B
Name: 20, dtype: str
Name    C
Name: 30, dtype: str

In [32]:
# 15.df.iloc[:, 1:3]

print(df.iloc[:, 1:3])

Empty DataFrame
Columns: []
Index: [10, 20, 30]

# Filtering (Boolean Filtering)

In [33]:
# 1.df[df['Age'] > 18]
# 2.df[df['City'] == 'Pune']
# 3.df[(df['Age'] > 18) & (df['City'] == 'Pune')]
# 4.df[df['Marks'].between(60, 90)]
# 5.df[df['Name'].str.contains('a')]

In [34]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Aarti", "karan", "tanvi", "shradha"],
    "Age" : [22, 23, 25, 30],
    "City": ["Pune", "Mumbai", "Pune", "Nagpur"],
    "Marks": [60, 90, 30, 78]
})
df

      Name  Age    City  Marks
0    Aarti   22    Pune     60
1    karan   23  Mumbai     90
2    tanvi   25    Pune     30
3  shradha   30  Nagpur     78

In [35]:
[df['Age'] > 18] # this condition satisfy then true value

[0    True
 1    True
 2    True
 3    True
 Name: Age, dtype: bool]

In [36]:
# 1.df[df['Age'] > 18]
df[df['Age'] > 18] # in this's df is to printout the condition satisfy values

      Name  Age    City  Marks
0    Aarti   22    Pune     60
1    karan   23  Mumbai     90
2    tanvi   25    Pune     30
3  shradha   30  Nagpur     78

In [37]:
# 2.df[df['City'] == 'Pune']
df[df['City'] == "Pune"]

    Name  Age  City  Marks
0  Aarti   22  Pune     60
2  tanvi   25  Pune     30

In [38]:
# 3.df[(df['Age'] > 18) & (df['City'] == 'Pune')]
df[(df['Age'] > 18) & (df['City'] == "Pune")]

    Name  Age  City  Marks
0  Aarti   22  Pune     60
2  tanvi   25  Pune     30

In [39]:
# 4.df[df['Marks'].between(60, 90)]

df[df['Marks'].between(65, 90)]

      Name  Age    City  Marks
1    karan   23  Mumbai     90
3  shradha   30  Nagpur     78

In [40]:
# 5.df[df['Name'].str.contains('a')]
df[df['Name'].str.contains('a')]

      Name  Age    City  Marks
0    Aarti   22    Pune     60
1    karan   23  Mumbai     90
2    tanvi   25    Pune     30
3  shradha   30  Nagpur     78

# class(pp)

In [41]:
import pandas as pd

data = {
    'id' : [1,2,3,4,5,6,7],
    'name' : ['aarti','priya','shyam','ram','meean','reena',None],
    'department' : ['IT','IT','Finance','Analyst','IT',None,None],
    'Salary': [20000,30000,40000,50000,60000,60000, None]
    
}
df = pd.DataFrame(data)
df

   id   name department   Salary
0   1  aarti         IT  20000.0
1   2  priya         IT  30000.0
2   3  shyam    Finance  40000.0
3   4    ram    Analyst  50000.0
4   5  meean         IT  60000.0
5   6  reena        NaN  60000.0
6   7    NaN        NaN      NaN

In [42]:
df.isnull().sum()

id            0
name          1
department    2
Salary        1
dtype: int64

In [43]:
df.fillna({'name': 'not mentioned'}, inplace = True)

   id           name department   Salary
0   1          aarti         IT  20000.0
1   2          priya         IT  30000.0
2   3          shyam    Finance  40000.0
3   4            ram    Analyst  50000.0
4   5          meean         IT  60000.0
5   6          reena        NaN  60000.0
6   7  not mentioned        NaN      NaN

In [44]:
df.loc[5,'department'] = 'Manager'
df

   id           name department   Salary
0   1          aarti         IT  20000.0
1   2          priya         IT  30000.0
2   3          shyam    Finance  40000.0
3   4            ram    Analyst  50000.0
4   5          meean         IT  60000.0
5   6          reena    Manager  60000.0
6   7  not mentioned        NaN      NaN

In [45]:
df.loc[6,'department'] = 'IT'
df

   id           name department   Salary
0   1          aarti         IT  20000.0
1   2          priya         IT  30000.0
2   3          shyam    Finance  40000.0
3   4            ram    Analyst  50000.0
4   5          meean         IT  60000.0
5   6          reena    Manager  60000.0
6   7  not mentioned         IT      NaN

In [46]:
df.fillna(df['Salary'].mean(), inplace = True)
df

   id           name department        Salary
0   1          aarti         IT  20000.000000
1   2          priya         IT  30000.000000
2   3          shyam    Finance  40000.000000
3   4            ram    Analyst  50000.000000
4   5          meean         IT  60000.000000
5   6          reena    Manager  60000.000000
6   7  not mentioned         IT  43333.333333

In [47]:
df.loc[len(df)] = [8, 'mahesh', 'HR', 90000]
df

   id           name department        Salary
0   1          aarti         IT  20000.000000
1   2          priya         IT  30000.000000
2   3          shyam    Finance  40000.000000
3   4            ram    Analyst  50000.000000
4   5          meean         IT  60000.000000
5   6          reena    Manager  60000.000000
6   7  not mentioned         IT  43333.333333
7   8         mahesh         HR  90000.000000

In [48]:
data1 = {
    'id' : [9,10, None],
    'name' : ['kavya', 'parth', None],
    'department' : ['IT', 'sales', None],
    'Salary' : [50000, 30000, None]
} 

df1 = pd.DataFrame(data1)
df1

     id   name department   Salary
0   9.0  kavya         IT  50000.0
1  10.0  parth      sales  30000.0
2   NaN    NaN        NaN      NaN

In [49]:
new_Data = pd.concat([df, df1])
new_Data

     id           name department        Salary
0   1.0          aarti         IT  20000.000000
1   2.0          priya         IT  30000.000000
2   3.0          shyam    Finance  40000.000000
3   4.0            ram    Analyst  50000.000000
4   5.0          meean         IT  60000.000000
5   6.0          reena    Manager  60000.000000
6   7.0  not mentioned         IT  43333.333333
7   8.0         mahesh         HR  90000.000000
0   9.0          kavya         IT  50000.000000
1  10.0          parth      sales  30000.000000
2   NaN            NaN        NaN           NaN

In [50]:
new_Data = pd.concat([df, df1], ignore_index = True)
new_Data

      id           name department        Salary
0    1.0          aarti         IT  20000.000000
1    2.0          priya         IT  30000.000000
2    3.0          shyam    Finance  40000.000000
3    4.0            ram    Analyst  50000.000000
4    5.0          meean         IT  60000.000000
5    6.0          reena    Manager  60000.000000
6    7.0  not mentioned         IT  43333.333333
7    8.0         mahesh         HR  90000.000000
8    9.0          kavya         IT  50000.000000
9   10.0          parth      sales  30000.000000
10   NaN            NaN        NaN           NaN

In [51]:
new_Data.dropna()

     id           name department        Salary
0   1.0          aarti         IT  20000.000000
1   2.0          priya         IT  30000.000000
2   3.0          shyam    Finance  40000.000000
3   4.0            ram    Analyst  50000.000000
4   5.0          meean         IT  60000.000000
5   6.0          reena    Manager  60000.000000
6   7.0  not mentioned         IT  43333.333333
7   8.0         mahesh         HR  90000.000000
8   9.0          kavya         IT  50000.000000
9  10.0          parth      sales  30000.000000

In [52]:
new_Data.dropna(inplace = True)
new_Data

     id           name department        Salary
0   1.0          aarti         IT  20000.000000
1   2.0          priya         IT  30000.000000
2   3.0          shyam    Finance  40000.000000
3   4.0            ram    Analyst  50000.000000
4   5.0          meean         IT  60000.000000
5   6.0          reena    Manager  60000.000000
6   7.0  not mentioned         IT  43333.333333
7   8.0         mahesh         HR  90000.000000
8   9.0          kavya         IT  50000.000000
9  10.0          parth      sales  30000.000000

In [53]:
data2 = {
    'id' : [9,10, None, 9],
    'name' : ['kavya', 'parth', None, 'kavya'],
    'department' : ['IT', 'sales', None, 'IT'],
    'Salary' : [50000, 30000, None, 50000]
} 

df2 = pd.DataFrame(data2)
df2

     id   name department   Salary
0   9.0  kavya         IT  50000.0
1  10.0  parth      sales  30000.0
2   NaN    NaN        NaN      NaN
3   9.0  kavya         IT  50000.0

In [54]:
new_Data1 = pd.concat([df, df2], ignore_index = True)
new_Data1

      id           name department        Salary
0    1.0          aarti         IT  20000.000000
1    2.0          priya         IT  30000.000000
2    3.0          shyam    Finance  40000.000000
3    4.0            ram    Analyst  50000.000000
4    5.0          meean         IT  60000.000000
5    6.0          reena    Manager  60000.000000
6    7.0  not mentioned         IT  43333.333333
7    8.0         mahesh         HR  90000.000000
8    9.0          kavya         IT  50000.000000
9   10.0          parth      sales  30000.000000
10   NaN            NaN        NaN           NaN
11   9.0          kavya         IT  50000.000000

In [55]:
new_Data1.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11     True
dtype: bool

In [56]:
new_Data1.drop_duplicates()

      id           name department        Salary
0    1.0          aarti         IT  20000.000000
1    2.0          priya         IT  30000.000000
2    3.0          shyam    Finance  40000.000000
3    4.0            ram    Analyst  50000.000000
4    5.0          meean         IT  60000.000000
5    6.0          reena    Manager  60000.000000
6    7.0  not mentioned         IT  43333.333333
7    8.0         mahesh         HR  90000.000000
8    9.0          kavya         IT  50000.000000
9   10.0          parth      sales  30000.000000
10   NaN            NaN        NaN           NaN

In [57]:
new_Data1.sort_values(by='Salary', ascending = True)

      id           name department        Salary
0    1.0          aarti         IT  20000.000000
1    2.0          priya         IT  30000.000000
9   10.0          parth      sales  30000.000000
2    3.0          shyam    Finance  40000.000000
6    7.0  not mentioned         IT  43333.333333
3    4.0            ram    Analyst  50000.000000
8    9.0          kavya         IT  50000.000000
11   9.0          kavya         IT  50000.000000
4    5.0          meean         IT  60000.000000
5    6.0          reena    Manager  60000.000000
7    8.0         mahesh         HR  90000.000000
10   NaN            NaN        NaN           NaN

In [58]:
new_Data1.sort_values(by=['department','Salary'], ascending = [False,False])

      id           name department        Salary
9   10.0          parth      sales  30000.000000
5    6.0          reena    Manager  60000.000000
4    5.0          meean         IT  60000.000000
8    9.0          kavya         IT  50000.000000
11   9.0          kavya         IT  50000.000000
6    7.0  not mentioned         IT  43333.333333
1    2.0          priya         IT  30000.000000
0    1.0          aarti         IT  20000.000000
7    8.0         mahesh         HR  90000.000000
2    3.0          shyam    Finance  40000.000000
3    4.0            ram    Analyst  50000.000000
10   NaN            NaN        NaN           NaN

In [59]:
new_Data1.sort_index()

      id           name department        Salary
0    1.0          aarti         IT  20000.000000
1    2.0          priya         IT  30000.000000
2    3.0          shyam    Finance  40000.000000
3    4.0            ram    Analyst  50000.000000
4    5.0          meean         IT  60000.000000
5    6.0          reena    Manager  60000.000000
6    7.0  not mentioned         IT  43333.333333
7    8.0         mahesh         HR  90000.000000
8    9.0          kavya         IT  50000.000000
9   10.0          parth      sales  30000.000000
10   NaN            NaN        NaN           NaN
11   9.0          kavya         IT  50000.000000