# Student Career Recommendation System

In [1]:
pip install pandas

Requirement already satisfied: pandas in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)

In [2]:
pip install numpy

Requirement already satisfied: numpy in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.4.4)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\hp\AppData\Local\Programs\Python\Python314\Lib\site-packages)

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("career1.csv")

In [5]:
df.head()

,Student_ID,Age,Gender,Education_Level,Stream,CGPA,Programming_Skill,Communication_Skill,Aptitude_Score,Interest_Area,Preferred_Work,Internship_Experience,Certifications,Career_Goal
0,STU001,18,Female,UG,IT,6.11,Beginner,9.0,45,Web Development,Hybrid,No,0,Job
1,STU002,21,Male,Diploma,Electronics,5.62,Beginner,9.0,66,Web Development,Remote,No,4,Job
2,STU003,24,Female,PG,IT,6.45,Intermediate,2.0,45,Data Science,Office,Yes,5,Higher Study
3,STU004,18,Female,Diploma,Computer Science,9.78,Intermediate,2.0,75,Finance,Office,No,3,Startup
4,STU005,18,Male,PG,Computer Science,9.26,Beginner,7.0,57,Web Development,Office,No,2,Higher Study

In [6]:
df.shape

(250, 14)

In [7]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Education_Level', 'Stream', 'CGPA',
       'Programming_Skill', 'Communication_Skill', 'Aptitude_Score',
       'Interest_Area', 'Preferred_Work', 'Internship_Experience',
       'Certifications', 'Career_Goal'],
      dtype='str')

In [8]:
df.isnull().sum()

Student_ID                0
Age                       0
Gender                    0
Education_Level           0
Stream                    0
CGPA                      9
Programming_Skill        10
Communication_Skill      10
Aptitude_Score            0
Interest_Area             8
Preferred_Work            3
Internship_Experience     4
Certifications            0
Career_Goal               0
dtype: int64

In [9]:
median_cgpa = np.median(
    df['CGPA'].dropna()
)

df['CGPA'] = df['CGPA'].fillna(
    median_cgpa
)
df.head(30)

,Student_ID,Age,Gender,Education_Level,Stream,CGPA,Programming_Skill,Communication_Skill,Aptitude_Score,Interest_Area,Preferred_Work,Internship_Experience,Certifications,Career_Goal
0,STU001,18,Female,UG,IT,6.11,Beginner,9.0,45,Web Development,Hybrid,No,0,Job
1,STU002,21,Male,Diploma,Electronics,5.62,Beginner,9.0,66,Web Development,Remote,No,4,Job
2,STU003,24,Female,PG,IT,6.45,Intermediate,2.0,45,Data Science,Office,Yes,5,Higher Study
3,STU004,18,Female,Diploma,Computer Science,9.78,Intermediate,2.0,75,Finance,Office,No,3,Startup
4,STU005,18,Male,PG,Computer Science,9.26,Beginner,7.0,57,Web Development,Office,No,2,Higher Study
5,STU006,21,Female,Diploma,Commerce,8.35,Advanced,3.0,74,Marketing,Hybrid,Yes,2,Higher Study
6,STU007,22,Male,Diploma,Mechanical,9.21,Beginner,4.0,92,Design,Remote,NaN,6,Higher Study
7,STU008,21,Female,UG,Commerce,7.70,NaN,8.0,49,Web Development,Office,Yes,3,Startup
8,STU009,27,Female,Diploma,Civil,7.09,NaN,NaN,71,Finance,Remote,Yes,1,Job
9,STU010,28,Female,Diploma,Computer Science,7.19,Advanced,8.0,73,Data Science,Office,Yes,1,Startup
10,STU011,28,Female,UG,Mechanical,7.41,Intermediate,1.0,86,Finance,Hybrid,No,8,Job
11,STU012,28,Female,Diploma,Electronics,8.18,Beginner,6.0,88,Web Development,Remote,Yes,5,Higher Study
12,STU013,19,Female,PG,IT,5.75,Advanced,2.0,45,AI,Hybrid,No,1,Startup
13,STU014,20,Female,Diploma,IT,6.67,Advanced,7.0,53,Data Science,Hybrid,Yes,4,Higher Study
14,STU015,25,Female,UG,IT,6.49,Intermediate,1.0,77,Marketing,Hybrid,Yes,3,Job
15,STU016,28,Male,UG,Computer Science,9.48,Intermediate,2.0,72,Web Development,Remote,No,7,Job
16,STU017,27,Female,UG,Arts,7.58,Intermediate,4.0,46,Data Science,Remote,No,5,Higher Study
17,STU018,25,Male,Diploma,Commerce,9.83,Beginner,1.0,65,Design,Hybrid,No,1,Job
18,STU019,21,Female,UG,Civil,6.31,Intermediate,4.0,95,Cybersecurity,Remote,No,8,Job
19,STU020,28,Male,UG,Arts,9.23,Beginner,7.0,71,AI,Office,Yes,6,Job
20,STU021,24,Male,PG,Mechanical,9.58,Intermediate,5.0,67,Data Science,Hybrid,No,2,Job
21,STU022,21,Male,Diploma,Commerce,7.89,Advanced,6.0,43,Finance,Remote,No,8,Startup
22,STU023,18,Male,UG,Computer Science,8.12,Advanced,4.0,65,NaN,Remote,Yes,0,Startup
23,STU024,24,Female,PG,IT,8.45,Intermediate,NaN,56,Web Development,Office,Yes,4,Higher Study
24,STU025,19,Male,PG,Electronics,9.89,Beginner,2.0,74,Marketing,Remote,No,2,Higher Study
25,STU026,21,Female,PG,IT,7.43,Advanced,5.0,79,Web Development,Hybrid,Yes,8,Higher Study
26,STU027,20,Female,UG,Computer Science,8.77,Beginner,5.0,58,Web Development,NaN,Yes,5,Job
27,STU028,26,Female,PG,Arts,5.72,Advanced,7.0,93,Finance,Office,Yes,0,Higher Study
28,STU029,28,Female,UG,Commerce,7.86,NaN,7.0,75,Data Science,Remote,Yes,1,Startup
29,STU030,26,Male,PG,Electronics,7.93,NaN,3.0,42,Data Science,Office,No,0,Higher Study

In [10]:
mode_skill = df[
'Programming_Skill'
].mode()[0]

df['Programming_Skill'] = df[
'Programming_Skill'
].fillna(mode_skill)
df.head(30)

,Student_ID,Age,Gender,Education_Level,Stream,CGPA,Programming_Skill,Communication_Skill,Aptitude_Score,Interest_Area,Preferred_Work,Internship_Experience,Certifications,Career_Goal
0,STU001,18,Female,UG,IT,6.11,Beginner,9.0,45,Web Development,Hybrid,No,0,Job
1,STU002,21,Male,Diploma,Electronics,5.62,Beginner,9.0,66,Web Development,Remote,No,4,Job
2,STU003,24,Female,PG,IT,6.45,Intermediate,2.0,45,Data Science,Office,Yes,5,Higher Study
3,STU004,18,Female,Diploma,Computer Science,9.78,Intermediate,2.0,75,Finance,Office,No,3,Startup
4,STU005,18,Male,PG,Computer Science,9.26,Beginner,7.0,57,Web Development,Office,No,2,Higher Study
5,STU006,21,Female,Diploma,Commerce,8.35,Advanced,3.0,74,Marketing,Hybrid,Yes,2,Higher Study
6,STU007,22,Male,Diploma,Mechanical,9.21,Beginner,4.0,92,Design,Remote,NaN,6,Higher Study
7,STU008,21,Female,UG,Commerce,7.70,Advanced,8.0,49,Web Development,Office,Yes,3,Startup
8,STU009,27,Female,Diploma,Civil,7.09,Advanced,NaN,71,Finance,Remote,Yes,1,Job
9,STU010,28,Female,Diploma,Computer Science,7.19,Advanced,8.0,73,Data Science,Office,Yes,1,Startup
10,STU011,28,Female,UG,Mechanical,7.41,Intermediate,1.0,86,Finance,Hybrid,No,8,Job
11,STU012,28,Female,Diploma,Electronics,8.18,Beginner,6.0,88,Web Development,Remote,Yes,5,Higher Study
12,STU013,19,Female,PG,IT,5.75,Advanced,2.0,45,AI,Hybrid,No,1,Startup
13,STU014,20,Female,Diploma,IT,6.67,Advanced,7.0,53,Data Science,Hybrid,Yes,4,Higher Study
14,STU015,25,Female,UG,IT,6.49,Intermediate,1.0,77,Marketing,Hybrid,Yes,3,Job
15,STU016,28,Male,UG,Computer Science,9.48,Intermediate,2.0,72,Web Development,Remote,No,7,Job
16,STU017,27,Female,UG,Arts,7.58,Intermediate,4.0,46,Data Science,Remote,No,5,Higher Study
17,STU018,25,Male,Diploma,Commerce,9.83,Beginner,1.0,65,Design,Hybrid,No,1,Job
18,STU019,21,Female,UG,Civil,6.31,Intermediate,4.0,95,Cybersecurity,Remote,No,8,Job
19,STU020,28,Male,UG,Arts,9.23,Beginner,7.0,71,AI,Office,Yes,6,Job
20,STU021,24,Male,PG,Mechanical,9.58,Intermediate,5.0,67,Data Science,Hybrid,No,2,Job
21,STU022,21,Male,Diploma,Commerce,7.89,Advanced,6.0,43,Finance,Remote,No,8,Startup
22,STU023,18,Male,UG,Computer Science,8.12,Advanced,4.0,65,NaN,Remote,Yes,0,Startup
23,STU024,24,Female,PG,IT,8.45,Intermediate,NaN,56,Web Development,Office,Yes,4,Higher Study
24,STU025,19,Male,PG,Electronics,9.89,Beginner,2.0,74,Marketing,Remote,No,2,Higher Study
25,STU026,21,Female,PG,IT,7.43,Advanced,5.0,79,Web Development,Hybrid,Yes,8,Higher Study
26,STU027,20,Female,UG,Computer Science,8.77,Beginner,5.0,58,Web Development,NaN,Yes,5,Job
27,STU028,26,Female,PG,Arts,5.72,Advanced,7.0,93,Finance,Office,Yes,0,Higher Study
28,STU029,28,Female,UG,Commerce,7.86,Advanced,7.0,75,Data Science,Remote,Yes,1,Startup
29,STU030,26,Male,PG,Electronics,7.93,Advanced,3.0,42,Data Science,Office,No,0,Higher Study

In [11]:
mean_communication = np.mean(
df['Communication_Skill'].dropna()
)

df['Communication_Skill'] = df[
'Communication_Skill'
].fillna(mean_communication)
df.head(30)

,Student_ID,Age,Gender,Education_Level,Stream,CGPA,Programming_Skill,Communication_Skill,Aptitude_Score,Interest_Area,Preferred_Work,Internship_Experience,Certifications,Career_Goal
0,STU001,18,Female,UG,IT,6.11,Beginner,9.000000,45,Web Development,Hybrid,No,0,Job
1,STU002,21,Male,Diploma,Electronics,5.62,Beginner,9.000000,66,Web Development,Remote,No,4,Job
2,STU003,24,Female,PG,IT,6.45,Intermediate,2.000000,45,Data Science,Office,Yes,5,Higher Study
3,STU004,18,Female,Diploma,Computer Science,9.78,Intermediate,2.000000,75,Finance,Office,No,3,Startup
4,STU005,18,Male,PG,Computer Science,9.26,Beginner,7.000000,57,Web Development,Office,No,2,Higher Study
5,STU006,21,Female,Diploma,Commerce,8.35,Advanced,3.000000,74,Marketing,Hybrid,Yes,2,Higher Study
6,STU007,22,Male,Diploma,Mechanical,9.21,Beginner,4.000000,92,Design,Remote,NaN,6,Higher Study
7,STU008,21,Female,UG,Commerce,7.70,Advanced,8.000000,49,Web Development,Office,Yes,3,Startup
8,STU009,27,Female,Diploma,Civil,7.09,Advanced,5.308333,71,Finance,Remote,Yes,1,Job
9,STU010,28,Female,Diploma,Computer Science,7.19,Advanced,8.000000,73,Data Science,Office,Yes,1,Startup
10,STU011,28,Female,UG,Mechanical,7.41,Intermediate,1.000000,86,Finance,Hybrid,No,8,Job
11,STU012,28,Female,Diploma,Electronics,8.18,Beginner,6.000000,88,Web Development,Remote,Yes,5,Higher Study
12,STU013,19,Female,PG,IT,5.75,Advanced,2.000000,45,AI,Hybrid,No,1,Startup
13,STU014,20,Female,Diploma,IT,6.67,Advanced,7.000000,53,Data Science,Hybrid,Yes,4,Higher Study
14,STU015,25,Female,UG,IT,6.49,Intermediate,1.000000,77,Marketing,Hybrid,Yes,3,Job
15,STU016,28,Male,UG,Computer Science,9.48,Intermediate,2.000000,72,Web Development,Remote,No,7,Job
16,STU017,27,Female,UG,Arts,7.58,Intermediate,4.000000,46,Data Science,Remote,No,5,Higher Study
17,STU018,25,Male,Diploma,Commerce,9.83,Beginner,1.000000,65,Design,Hybrid,No,1,Job
18,STU019,21,Female,UG,Civil,6.31,Intermediate,4.000000,95,Cybersecurity,Remote,No,8,Job
19,STU020,28,Male,UG,Arts,9.23,Beginner,7.000000,71,AI,Office,Yes,6,Job
20,STU021,24,Male,PG,Mechanical,9.58,Intermediate,5.000000,67,Data Science,Hybrid,No,2,Job
21,STU022,21,Male,Diploma,Commerce,7.89,Advanced,6.000000,43,Finance,Remote,No,8,Startup
22,STU023,18,Male,UG,Computer Science,8.12,Advanced,4.000000,65,NaN,Remote,Yes,0,Startup
23,STU024,24,Female,PG,IT,8.45,Intermediate,5.308333,56,Web Development,Office,Yes,4,Higher Study
24,STU025,19,Male,PG,Electronics,9.89,Beginner,2.000000,74,Marketing,Remote,No,2,Higher Study
25,STU026,21,Female,PG,IT,7.43,Advanced,5.000000,79,Web Development,Hybrid,Yes,8,Higher Study
26,STU027,20,Female,UG,Computer Science,8.77,Beginner,5.000000,58,Web Development,NaN,Yes,5,Job
27,STU028,26,Female,PG,Arts,5.72,Advanced,7.000000,93,Finance,Office,Yes,0,Higher Study
28,STU029,28,Female,UG,Commerce,7.86,Advanced,7.000000,75,Data Science,Remote,Yes,1,Startup
29,STU030,26,Male,PG,Electronics,7.93,Advanced,3.000000,42,Data Science,Office,No,0,Higher Study

In [12]:
df['Interest_Area'] = df[
'Interest_Area'
].fillna('Unknown')

df['Preferred_Work'] = df[
'Preferred_Work'
].fillna('Hybrid')

df['Internship_Experience'] = df[
'Internship_Experience'
].fillna('No')

df.head(30)

,Student_ID,Age,Gender,Education_Level,Stream,CGPA,Programming_Skill,Communication_Skill,Aptitude_Score,Interest_Area,Preferred_Work,Internship_Experience,Certifications,Career_Goal
0,STU001,18,Female,UG,IT,6.11,Beginner,9.000000,45,Web Development,Hybrid,No,0,Job
1,STU002,21,Male,Diploma,Electronics,5.62,Beginner,9.000000,66,Web Development,Remote,No,4,Job
2,STU003,24,Female,PG,IT,6.45,Intermediate,2.000000,45,Data Science,Office,Yes,5,Higher Study
3,STU004,18,Female,Diploma,Computer Science,9.78,Intermediate,2.000000,75,Finance,Office,No,3,Startup
4,STU005,18,Male,PG,Computer Science,9.26,Beginner,7.000000,57,Web Development,Office,No,2,Higher Study
5,STU006,21,Female,Diploma,Commerce,8.35,Advanced,3.000000,74,Marketing,Hybrid,Yes,2,Higher Study
6,STU007,22,Male,Diploma,Mechanical,9.21,Beginner,4.000000,92,Design,Remote,No,6,Higher Study
7,STU008,21,Female,UG,Commerce,7.70,Advanced,8.000000,49,Web Development,Office,Yes,3,Startup
8,STU009,27,Female,Diploma,Civil,7.09,Advanced,5.308333,71,Finance,Remote,Yes,1,Job
9,STU010,28,Female,Diploma,Computer Science,7.19,Advanced,8.000000,73,Data Science,Office,Yes,1,Startup
10,STU011,28,Female,UG,Mechanical,7.41,Intermediate,1.000000,86,Finance,Hybrid,No,8,Job
11,STU012,28,Female,Diploma,Electronics,8.18,Beginner,6.000000,88,Web Development,Remote,Yes,5,Higher Study
12,STU013,19,Female,PG,IT,5.75,Advanced,2.000000,45,AI,Hybrid,No,1,Startup
13,STU014,20,Female,Diploma,IT,6.67,Advanced,7.000000,53,Data Science,Hybrid,Yes,4,Higher Study
14,STU015,25,Female,UG,IT,6.49,Intermediate,1.000000,77,Marketing,Hybrid,Yes,3,Job
15,STU016,28,Male,UG,Computer Science,9.48,Intermediate,2.000000,72,Web Development,Remote,No,7,Job
16,STU017,27,Female,UG,Arts,7.58,Intermediate,4.000000,46,Data Science,Remote,No,5,Higher Study
17,STU018,25,Male,Diploma,Commerce,9.83,Beginner,1.000000,65,Design,Hybrid,No,1,Job
18,STU019,21,Female,UG,Civil,6.31,Intermediate,4.000000,95,Cybersecurity,Remote,No,8,Job
19,STU020,28,Male,UG,Arts,9.23,Beginner,7.000000,71,AI,Office,Yes,6,Job
20,STU021,24,Male,PG,Mechanical,9.58,Intermediate,5.000000,67,Data Science,Hybrid,No,2,Job
21,STU022,21,Male,Diploma,Commerce,7.89,Advanced,6.000000,43,Finance,Remote,No,8,Startup
22,STU023,18,Male,UG,Computer Science,8.12,Advanced,4.000000,65,Unknown,Remote,Yes,0,Startup
23,STU024,24,Female,PG,IT,8.45,Intermediate,5.308333,56,Web Development,Office,Yes,4,Higher Study
24,STU025,19,Male,PG,Electronics,9.89,Beginner,2.000000,74,Marketing,Remote,No,2,Higher Study
25,STU026,21,Female,PG,IT,7.43,Advanced,5.000000,79,Web Development,Hybrid,Yes,8,Higher Study
26,STU027,20,Female,UG,Computer Science,8.77,Beginner,5.000000,58,Web Development,Hybrid,Yes,5,Job
27,STU028,26,Female,PG,Arts,5.72,Advanced,7.000000,93,Finance,Office,Yes,0,Higher Study
28,STU029,28,Female,UG,Commerce,7.86,Advanced,7.000000,75,Data Science,Remote,Yes,1,Startup
29,STU030,26,Male,PG,Electronics,7.93,Advanced,3.000000,42,Data Science,Office,No,0,Higher Study

In [13]:
df.duplicated().sum()

np.int64(7)

In [14]:
df.shape

(250, 14)

In [15]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
df.shape

(243, 14)

In [18]:
import pandas as pd

# all rows
pd.set_option('display.max_rows', None)

# all columns
pd.set_option('display.max_columns', None)

# full column content
pd.set_option('display.max_colwidth', None)

# Auto adjust width
pd.set_option('display.width', None)

recommended_career = [] 

for interest in df['Interest_Area']:

    if interest == 'AI':
        recommended_career.append('Data Scientist')

    elif interest == 'Data Science':
        recommended_career.append('Data Analyst')

    elif interest == 'Web Development':
        recommended_career.append('Software Engineer')

    elif interest == 'Cybersecurity':
        recommended_career.append('Cybersecurity Analyst')

    elif interest == 'Finance':
        recommended_career.append('Financial Analyst')

    elif interest == 'Marketing':
        recommended_career.append('Digital Marketing Specialist')

    elif interest == 'Design':
        recommended_career.append('UI/UX Designer')

    elif interest == 'Cloud Computing':
        recommended_career.append('Cloud Engineer')

    else:
        recommended_career.append('Career Counselling Needed')

# Create new column
df['Recommended_Career'] = recommended_career

# Show complete dataframe
df

,Student_ID,Age,Gender,Education_Level,Stream,CGPA,Programming_Skill,Communication_Skill,Aptitude_Score,Interest_Area,Preferred_Work,Internship_Experience,Certifications,Career_Goal,Recommended_Career
0,STU001,18,Female,UG,IT,6.11,Beginner,9.000000,45,Web Development,Hybrid,No,0,Job,Software Engineer
1,STU002,21,Male,Diploma,Electronics,5.62,Beginner,9.000000,66,Web Development,Remote,No,4,Job,Software Engineer
2,STU003,24,Female,PG,IT,6.45,Intermediate,2.000000,45,Data Science,Office,Yes,5,Higher Study,Data Analyst
3,STU004,18,Female,Diploma,Computer Science,9.78,Intermediate,2.000000,75,Finance,Office,No,3,Startup,Financial Analyst
4,STU005,18,Male,PG,Computer Science,9.26,Beginner,7.000000,57,Web Development,Office,No,2,Higher Study,Software Engineer
5,STU006,21,Female,Diploma,Commerce,8.35,Advanced,3.000000,74,Marketing,Hybrid,Yes,2,Higher Study,Digital Marketing Specialist
6,STU007,22,Male,Diploma,Mechanical,9.21,Beginner,4.000000,92,Design,Remote,No,6,Higher Study,UI/UX Designer
7,STU008,21,Female,UG,Commerce,7.70,Advanced,8.000000,49,Web Development,Office,Yes,3,Startup,Software Engineer
8,STU009,27,Female,Diploma,Civil,7.09,Advanced,5.308333,71,Finance,Remote,Yes,1,Job,Financial Analyst
9,STU010,28,Female,Diploma,Computer Science,7.19,Advanced,8.000000,73,Data Science,Office,Yes,1,Startup,Data Analyst
10,STU011,28,Female,UG,Mechanical,7.41,Intermediate,1.000000,86,Finance,Hybrid,No,8,Job,Financial Analyst
11,STU012,28,Female,Diploma,Electronics,8.18,Beginner,6.000000,88,Web Development,Remote,Yes,5,Higher Study,Software Engineer
12,STU013,19,Female,PG,IT,5.75,Advanced,2.000000,45,AI,Hybrid,No,1,Startup,Data Scientist
13,STU014,20,Female,Diploma,IT,6.67,Advanced,7.000000,53,Data Science,Hybrid,Yes,4,Higher Study,Data Analyst
14,STU015,25,Female,UG,IT,6.49,Intermediate,1.000000,77,Marketing,Hybrid,Yes,3,Job,Digital Marketing Specialist
15,STU016,28,Male,UG,Computer Science,9.48,Intermediate,2.000000,72,Web Development,Remote,No,7,Job,Software Engineer
16,STU017,27,Female,UG,Arts,7.58,Intermediate,4.000000,46,Data Science,Remote,No,5,Higher Study,Data Analyst
17,STU018,25,Male,Diploma,Commerce,9.83,Beginner,1.000000,65,Design,Hybrid,No,1,Job,UI/UX Designer
18,STU019,21,Female,UG,Civil,6.31,Intermediate,4.000000,95,Cybersecurity,Remote,No,8,Job,Cybersecurity Analyst
19,STU020,28,Male,UG,Arts,9.23,Beginner,7.000000,71,AI,Office,Yes,6,Job,Data Scientist
20,STU021,24,Male,PG,Mechanical,9.58,Intermediate,5.000000,67,Data Science,Hybrid,No,2,Job,Data Analyst
21,STU022,21,Male,Diploma,Commerce,7.89,Advanced,6.000000,43,Finance,Remote,No,8,Startup,Financial Analyst
22,STU023,18,Male,UG,Computer Science,8.12,Advanced,4.000000,65,Unknown,Remote,Yes,0,Startup,Career Counselling Needed
23,STU024,24,Female,PG,IT,8.45,Intermediate,5.308333,56,Web Development,Office,Yes,4,Higher Study,Software Engineer
24,STU025,19,Male,PG,Electronics,9.89,Beginner,2.000000,74,Marketing,Remote,No,2,Higher Study,Digital Marketing Specialist
25,STU026,21,Female,PG,IT,7.43,Advanced,5.000000,79,Web Development,Hybrid,Yes,8,Higher Study,Software Engineer
26,STU027,20,Female,UG,Computer Science,8.77,Beginner,5.000000,58,Web Development,Hybrid,Yes,5,Job,Software Engineer
27,STU028,26,Female,PG,Arts,5.72,Advanced,7.000000,93,Finance,Office,Yes,0,Higher Study,Financial Analyst
28,STU029,28,Female,UG,Commerce,7.86,Advanced,7.000000,75,Data Science,Remote,Yes,1,Startup,Data Analyst
29,STU030,26,Male,PG,Electronics,7.93,Advanced,3.000000,42,Data Science,Office,No,0,Higher Study,Data Analyst
30,STU031,28,Male,Diploma,Computer Science,7.06,Advanced,7.000000,79,Cybersecurity,Hybrid,Yes,3,Job,Cybersecurity Analyst
31,STU032,24,Male,UG,Commerce,9.57,Intermediate,4.000000,57,Data Science,Remote,Yes,6,Job,Data Analyst
32,STU033,21,Male,PG,Mechanical,6.84,Beginner,4.000000,41,Cloud Computing,Hybrid,Yes,6,Higher Study,Cloud Engineer
33,STU034,19,Female,PG,Commerce,7.74,Advanced,9.000000,61,Finance,Remote,Yes,4,Job,Financial Analyst
34,STU035,18,Male,Diploma,Civil,7.02,Intermediate,7.000000,78,Finance,Hybrid,Yes,6,Startup,Financial Analyst
35,STU036,22,Male,Diploma,Civil,5.51,Advanced,4.000000,63,Cybersecurity,Office,Yes,5,Startup,Cybersecurity Analyst
36,STU037,28,Male,Diploma,Mechanical,7.73,Advanced,7.000000,60,Marketing,Office,No,8,Job,Digital Marketing Specialist
37,STU038,24,Female,Diploma,Commerce,9.47,Advanced,10.000000,59,Cybersecurity,Office,Yes,4,Higher Study,Cybersecurity Analyst
38,STU039,24,Female,PG,Civil,7.45,Beginner,9.000000,70,Cybersecurity,Hybrid,Yes,1,Higher Study,Cybersecurity Analyst
39,STU040,19,Male,Diploma,Mechanical,6.49,Beginner,3.000000,41,Marketing,Remote,Yes,7,Startup,Digital Marketing Specialist
40,STU041,25,Female,Diploma,Electronics,6.36,Advanced,7.000000,71,Web Development,Office,Yes,2,Startup,Software Engineer
41,STU042,19,Female,UG,IT,9.04,Advanced,9.000000,69,AI,Remote,Yes,1,Higher Study,Data Scientist
42,STU043,25,Female,PG,Electronics,9.09,Advanced,7.000000,93,Data Science,Hybrid,No,2,Startup,Data Analyst
43,STU044,25,Female,UG,Arts,8.31,Advanced,8.000000,80,Unknown,Remote,No,7,Job,Career Counselling Needed
44,STU045,21,Female,PG,Mechanical,9.43,Beginner,3.000000,49,Finance,Remote,No,2,Startup,Financial Analyst
45,STU046,19,Female,PG,Mechanical,7.89,Intermediate,1.000000,53,Cybersecurity,Office,No,0,Startup,Cybersecurity Analyst
46,STU047,25,Male,PG,Mechanical,8.82,Intermediate,9.000000,87,Design,Hybrid,Yes,7,Job,UI/UX Designer
47,STU048,24,Female,UG,Civil,6.98,Advanced,7.000000,86,Finance,Remote,No,2,Startup,Financial Analyst
48,STU049,24,Male,UG,Commerce,7.39,Intermediate,3.000000,43,AI,Office,No,5,Job,Data Scientist
49,STU050,23,Female,PG,Mechanical,8.81,Intermediate,5.000000,93,Cloud Computing,Remote,No,0,Startup,Cloud Engineer
50,STU051,23,Male,Diploma,Computer Science,8.94,Advanced,1.000000,88,AI,Remote,Yes,3,Job,Data Scientist
51,STU052,21,Male,PG,Commerce,6.00,Beginner,8.000000,84,Data Science,Office,No,2,Startup,Data Analyst
52,STU053,20,Female,UG,Electronics,5.61,Intermediate,10.000000,83,Web Development,Office,No,3,Job,Software Engineer
53,STU054,19,Female,Diploma,Electronics,9.04,Advanced,1.000000,62,Cybersecurity,Hybrid,No,5,Job,Cybersecurity Analyst
54,STU055,18,Female,PG,Computer Science,7.41,Intermediate,8.000000,85,Marketing,Remote,No,2,Startup,Digital Marketing Specialist
55,STU056,27,Female,PG,Civil,7.86,Advanced,5.000000,60,Finance,Remote,Yes,4,Higher Study,Financial Analyst
56,STU057,25,Female,PG,Computer Science,7.67,Intermediate,3.000000,71,Cybersecurity,Remote,No,4,Higher Study,Cybersecurity Analyst
57,STU058,27,Female,Diploma,Computer Science,7.86,Beginner,2.000000,55,Unknown,Hybrid,No,7,Startup,Career Counselling Needed
58,STU059,25,Female,PG,Arts,5.58,Intermediate,4.000000,65,Cybersecurity,Hybrid,Yes,4,Startup,Cybersecurity Analyst
59,STU060,25,Female,PG,Commerce,7.86,Intermediate,8.000000,57,Marketing,Office,No,3,Job,Digital Marketing Specialist
60,STU061,23,Male,Diploma,Electronics,9.68,Advanced,3.000000,52,Cybersecurity,Remote,No,4,Startup,Cybersecurity Analyst
61,STU062,19,Male,PG,IT,7.09,Intermediate,1.000000,85,Finance,Hybrid,Yes,4,Job,Financial Analyst
62,STU063,26,Female,Diploma,IT,8.31,Intermediate,2.000000,95,AI,Hybrid,No,7,Higher Study,Data Scientist
63,STU064,23,Male,UG,Mechanical,9.64,Intermediate,2.000000,92,Cloud Computing,Remote,No,7,Job,Cloud Engineer
64,STU065,20,Male,Diploma,Mechanical,5.87,Beginner,2.000000,75,AI,Office,Yes,8,Higher Study,Data Scientist
65,STU066,25,Female,Diploma,Civil,6.84,Advanced,1.000000,79,Cloud Computing,Hybrid,Yes,3,Startup,Cloud Engineer
66,STU067,22,Male,UG,IT,6.26,Beginner,3.000000,40,Cybersecurity,Office,No,7,Higher Study,Cybersecurity Analyst
67,STU068,21,Female,Diploma,Mechanical,8.59,Intermediate,2.000000,83,AI,Remote,No,3,Higher Study,Data Scientist
68,STU069,26,Male,Diploma,IT,9.50,Beginner,2.000000,43,Web Development,Remote,No,4,Higher Study,Software Engineer
69,STU070,25,Female,Diploma,Civil,9.65,Advanced,9.000000,71,Web Development,Office,Yes,0,Higher Study,Software Engineer
70,STU071,27,Female,UG,Computer Science,6.51,Advanced,5.308333,77,Marketing,Remote,No,0,Job,Digital Marketing Specialist
71,STU072,26,Female,PG,IT,9.89,Intermediate,8.000000,45,Cloud Computing,Office,No,6,Higher Study,Cloud Engineer
72,STU073,28,Male,UG,Mechanical,7.31,Intermediate,5.000000,82,Marketing,Office,Yes,7,Job,Digital Marketing Specialist
73,STU074,22,Female,UG,Arts,7.28,Advanced,1.000000,82,Marketing,Hybrid,No,6,Job,Digital Marketing Specialist
74,STU075,26,Female,Diploma,Arts,7.69,Intermediate,1.000000,53,Cybersecurity,Office,Yes,4,Higher Study,Cybersecurity Analyst
75,STU076,19,Male,Diploma,Electronics,9.02,Advanced,3.000000,59,Cloud Computing,Hybrid,Yes,8,Higher Study,Cloud Engineer
76,STU077,21,Male,PG,Computer Science,8.35,Beginner,8.000000,99,Web Development,Hybrid,No,8,Startup,Software Engineer
77,STU078,24,Female,PG,IT,7.51,Beginner,7.000000,52,Finance,Hybrid,Yes,1,Higher Study,Financial Analyst
78,STU079,23,Female,UG,Mechanical,8.69,Advanced,10.000000,82,Design,Office,Yes,7,Startup,UI/UX Designer
79,STU080,23,Female,Diploma,Arts,7.89,Intermediate,6.000000,95,Cloud Computing,Remote,Yes,6,Job,Cloud Engineer
80,STU081,18,Female,Diploma,Civil,8.60,Intermediate,7.000000,82,Design,Hybrid,Yes,7,Job,UI/UX Designer
81,STU082,26,Female,UG,Arts,9.22,Beginner,9.000000,98,Data Science,Office,Yes,2,Higher Study,Data Analyst
82,STU083,19,Female,PG,Mechanical,8.24,Intermediate,2.000000,94,Data Science,Office,No,5,Startup,Data Analyst
83,STU084,26,Male,Diploma,Computer Science,6.53,Advanced,5.000000,54,Cloud Computing,Hybrid,Yes,6,Job,Cloud Engineer
84,STU085,25,Male,Diploma,Mechanical,9.48,Beginner,6.000000,90,Web Development,Remote,No,5,Higher Study,Software Engineer
85,STU086,20,Male,Diploma,Civil,7.99,Beginner,3.000000,51,Design,Remote,No,3,Higher Study,UI/UX Designer
86,STU087,21,Female,Diploma,Mechanical,7.52,Advanced,1.000000,97,Data Science,Office,No,8,Job,Data Analyst
87,STU088,25,Female,Diploma,Mechanical,8.31,Intermediate,5.000000,69,Web Development,Office,Yes,6,Higher Study,Software Engineer
88,STU089,21,Female,Diploma,Mechanical,8.03,Advanced,5.000000,41,Web Development,Hybrid,No,4,Job,Software Engineer
89,STU090,27,Female,PG,Arts,9.01,Advanced,6.000000,54,AI,Hybrid,Yes,4,Startup,Data Scientist
90,STU091,28,Male,Diploma,Commerce,5.67,Intermediate,1.000000,77,Data Science,Office,Yes,1,Higher Study,Data Analyst
91,STU092,24,Male,UG,IT,8.96,Intermediate,9.000000,72,Marketing,Office,Yes,4,Higher Study,Digital Marketing Specialist
92,STU093,23,Male,PG,Computer Science,6.12,Beginner,7.000000,94,Finance,Hybrid,No,1,Higher Study,Financial Analyst
93,STU094,22,Male,PG,Mechanical,8.46,Advanced,5.000000,77,AI,Office,No,1,Startup,Data Scientist
94,STU095,25,Male,Diploma,Electronics,6.94,Advanced,4.000000,81,Cybersecurity,Remote,No,4,Startup,Cybersecurity Analyst
95,STU096,19,Male,UG,Computer Science,6.84,Intermediate,2.000000,46,Design,Remote,Yes,6,Higher Study,UI/UX Designer
96,STU097,28,Female,Diploma,Commerce,8.70,Intermediate,2.000000,93,Marketing,Office,No,4,Job,Digital Marketing Specialist
97,STU098,21,Female,PG,IT,9.26,Beginner,6.000000,74,Marketing,Hybrid,No,0,Higher Study,Digital Marketing Specialist
98,STU099,21,Male,PG,Computer Science,8.42,Advanced,10.000000,41,Finance,Remote,No,3,Job,Financial Analyst
99,STU100,19,Male,Diploma,IT,9.08,Beginner,6.000000,89,Cybersecurity,Remote,Yes,4,Job,Cybersecurity Analyst
100,STU101,26,Female,UG,Computer Science,8.41,Beginner,3.000000,40,Data Science,Office,Yes,5,Job,Data Analyst
101,STU102,22,Male,UG,Commerce,7.35,Beginner,2.000000,70,Data Science,Office,No,8,Startup,Data Analyst
102,STU103,25,Male,Diploma,Computer Science,8.70,Advanced,9.000000,59,Web Development,Office,Yes,0,Higher Study,Software Engineer
103,STU104,24,Male,PG,Commerce,9.50,Beginner,2.000000,60,Design,Hybrid,Yes,1,Job,UI/UX Designer
104,STU105,27,Female,PG,Electronics,7.83,Intermediate,9.000000,78,Finance,Office,Yes,1,Startup,Financial Analyst
105,STU106,24,Female,UG,Civil,6.99,Intermediate,7.000000,66,Cybersecurity,Hybrid,Yes,5,Higher Study,Cybersecurity Analyst
106,STU107,28,Female,PG,IT,8.52,Intermediate,2.000000,45,Marketing,Remote,Yes,6,Job,Digital Marketing Specialist
107,STU108,20,Male,Diploma,Electronics,7.97,Advanced,2.000000,66,Marketing,Office,No,0,Higher Study,Digital Marketing Specialist
108,STU109,23,Male,Diploma,Electronics,6.44,Advanced,5.308333,54,Finance,Remote,No,8,Higher Study,Financial Analyst
109,STU110,22,Male,PG,Arts,7.97,Advanced,10.000000,83,Web Development,Hybrid,Yes,4,Job,Software Engineer
110,STU111,22,Female,PG,Mechanical,5.53,Beginner,10.000000,82,Data Science,Office,Yes,2,Startup,Data Analyst
111,STU112,19,Male,PG,Civil,7.50,Beginner,6.000000,59,AI,Hybrid,No,1,Job,Data Scientist
112,STU113,20,Male,Diploma,Computer Science,6.70,Advanced,7.000000,71,Data Science,Hybrid,No,6,Higher Study,Data Analyst
113,STU114,26,Male,PG,Civil,5.99,Advanced,10.000000,71,Cybersecurity,Hybrid,No,0,Job,Cybersecurity Analyst
114,STU115,27,Male,UG,IT,6.83,Beginner,3.000000,88,Design,Office,No,5,Job,UI/UX Designer
115,STU116,25,Female,UG,IT,7.17,Advanced,4.000000,72,AI,Hybrid,No,1,Higher Study,Data Scientist
116,STU117,24,Male,PG,Computer Science,9.29,Advanced,7.000000,76,AI,Office,No,4,Job,Data Scientist
117,STU118,18,Female,UG,Arts,9.67,Advanced,6.000000,45,Design,Office,Yes,3,Higher Study,UI/UX Designer
118,STU119,26,Male,PG,Arts,6.87,Intermediate,4.000000,61,Design,Remote,Yes,8,Startup,UI/UX Designer
119,STU120,26,Male,PG,Mechanical,8.70,Advanced,3.000000,55,Web Development,Remote,Yes,4,Job,Software Engineer
120,STU121,27,Male,Diploma,Computer Science,6.28,Advanced,8.000000,69,Data Science,Hybrid,No,5,Startup,Data Analyst
121,STU122,20,Female,UG,Civil,7.45,Intermediate,5.000000,77,Marketing,Remote,No,8,Job,Digital Marketing Specialist
122,STU123,25,Female,UG,Computer Science,7.12,Intermediate,2.000000,81,Finance,Remote,No,7,Startup,Financial Analyst
123,STU124,25,Male,PG,Electronics,7.59,Beginner,1.000000,68,AI,Remote,No,1,Startup,Data Scientist
124,STU125,18,Male,Diploma,Civil,9.86,Advanced,9.000000,79,Data Science,Remote,No,5,Higher Study,Data Analyst
125,STU126,24,Female,Diploma,Electronics,5.73,Advanced,6.000000,44,Design,Office,Yes,8,Startup,UI/UX Designer
126,STU127,22,Female,Diploma,Arts,8.39,Advanced,5.308333,61,Design,Remote,Yes,5,Higher Study,UI/UX Designer
127,STU128,20,Male,PG,Electronics,7.16,Intermediate,3.000000,82,Design,Hybrid,Yes,6,Startup,UI/UX Designer
128,STU129,18,Female,PG,IT,9.69,Intermediate,8.000000,52,Marketing,Remote,Yes,2,Job,Digital Marketing Specialist
129,STU130,19,Male,Diploma,Mechanical,9.36,Advanced,3.000000,78,Unknown,Office,Yes,2,Job,Career Counselling Needed
130,STU131,25,Male,PG,Mechanical,8.48,Beginner,8.000000,79,Unknown,Office,No,3,Startup,Career Counselling Needed
131,STU132,22,Female,UG,Mechanical,8.48,Advanced,8.000000,69,Cybersecurity,Office,No,8,Startup,Cybersecurity Analyst
132,STU133,20,Male,Diploma,IT,9.34,Beginner,8.000000,95,Design,Office,Yes,8,Job,UI/UX Designer
133,STU134,19,Male,PG,Civil,9.48,Beginner,7.000000,45,Finance,Remote,No,5,Job,Financial Analyst
134,STU135,18,Female,Diploma,Mechanical,6.54,Beginner,6.000000,54,Design,Remote,No,1,Startup,UI/UX Designer
135,STU136,20,Male,UG,Mechanical,9.54,Intermediate,3.000000,88,Marketing,Hybrid,No,7,Startup,Digital Marketing Specialist
136,STU137,19,Male,PG,IT,9.17,Advanced,10.000000,73,AI,Office,Yes,4,Job,Data Scientist
137,STU138,19,Male,UG,Civil,8.31,Advanced,8.000000,44,Unknown,Remote,No,8,Job,Career Counselling Needed
138,STU139,20,Female,PG,Computer Science,8.21,Beginner,10.000000,66,Cybersecurity,Remote,Yes,8,Higher Study,Cybersecurity Analyst
139,STU140,26,Male,PG,Arts,7.57,Advanced,7.000000,63,Web Development,Office,No,5,Job,Software Engineer
140,STU141,21,Male,Diploma,Commerce,7.86,Beginner,1.000000,62,Marketing,Hybrid,No,2,Startup,Digital Marketing Specialist
141,STU142,25,Male,UG,Computer Science,8.65,Intermediate,1.000000,58,Cloud Computing,Remote,Yes,3,Job,Cloud Engineer
142,STU143,22,Female,Diploma,Civil,6.61,Advanced,4.000000,58,Marketing,Office,Yes,5,Higher Study,Digital Marketing Specialist
143,STU144,23,Female,PG,Commerce,7.43,Intermediate,6.000000,51,Web Development,Office,No,5,Startup,Software Engineer
144,STU145,19,Female,UG,Civil,8.15,Beginner,5.308333,58,Finance,Office,Yes,1,Higher Study,Financial Analyst
145,STU146,22,Female,Diploma,Commerce,7.37,Advanced,8.000000,62,Finance,Office,Yes,5,Startup,Financial Analyst
146,STU147,22,Male,UG,Commerce,8.31,Advanced,9.000000,91,Design,Hybrid,Yes,0,Job,UI/UX Designer
147,STU148,18,Male,UG,IT,8.93,Intermediate,6.000000,64,Cloud Computing,Hybrid,Yes,2,Startup,Cloud Engineer
148,STU149,23,Female,PG,Arts,5.84,Beginner,9.000000,63,Cloud Computing,Office,No,4,Job,Cloud Engineer
149,STU150,18,Male,PG,Electronics,7.20,Advanced,2.000000,56,Web Development,Office,No,3,Startup,Software Engineer
150,STU151,25,Male,UG,IT,9.25,Intermediate,3.000000,97,Finance,Hybrid,No,1,Startup,Financial Analyst
151,STU152,28,Female,Diploma,Computer Science,7.92,Intermediate,5.308333,94,Marketing,Remote,Yes,5,Startup,Digital Marketing Specialist
152,STU153,19,Male,UG,IT,8.98,Beginner,6.000000,75,Cybersecurity,Hybrid,No,7,Startup,Cybersecurity Analyst
153,STU154,27,Male,UG,Mechanical,7.25,Advanced,8.000000,73,Data Science,Office,No,1,Job,Data Analyst
154,STU155,28,Male,PG,Civil,7.86,Intermediate,3.000000,96,Marketing,Hybrid,Yes,2,Higher Study,Digital Marketing Specialist
155,STU156,19,Male,PG,IT,6.21,Advanced,4.000000,62,AI,Hybrid,No,1,Higher Study,Data Scientist
156,STU157,28,Female,UG,Commerce,6.83,Advanced,2.000000,72,Cybersecurity,Hybrid,Yes,2,Job,Cybersecurity Analyst
157,STU158,27,Male,UG,computer science,5.70,Advanced,10.000000,56,Marketing,Hybrid,Yes,6,Startup,Digital Marketing Specialist
158,STU159,25,Female,Diploma,Mechanical,7.62,Advanced,7.000000,59,AI,Office,Yes,0,Job,Data Scientist
159,STU160,24,Female,PG,IT,7.00,Beginner,6.000000,95,Cloud Computing,Hybrid,No,5,Higher Study,Cloud Engineer
160,STU161,23,Male,PG,IT,7.55,Intermediate,8.000000,55,Data Science,Remote,Yes,0,Higher Study,Data Analyst
161,STU162,27,Female,UG,Arts,9.47,Intermediate,10.000000,86,Design,Office,Yes,2,Higher Study,UI/UX Designer
162,STU163,25,Female,PG,Computer Science,5.90,Intermediate,9.000000,69,Cloud Computing,Remote,Yes,5,Job,Cloud Engineer
163,STU164,22,Female,Diploma,Arts,8.38,Intermediate,5.000000,74,AI,Hybrid,Yes,6,Job,Data Scientist
164,STU165,23,Female,PG,Computer Science,7.26,Advanced,9.000000,52,Finance,Office,No,1,Higher Study,Financial Analyst
165,STU166,26,Female,Diploma,Commerce,8.19,Beginner,2.000000,65,Cloud Computing,Office,No,8,Higher Study,Cloud Engineer
166,STU167,21,Female,Diploma,Computer Science,5.70,Beginner,6.000000,91,Data Science,Office,No,2,Startup,Data Analyst
167,STU168,23,Female,UG,Civil,9.86,Advanced,5.000000,77,Data Science,Office,No,4,Higher Study,Data Analyst
168,STU169,23,Female,Diploma,Computer Science,9.81,Advanced,5.000000,90,AI,Hybrid,Yes,7,Higher Study,Data Scientist
169,STU170,18,Female,UG,Electronics,8.27,Advanced,7.000000,49,Cybersecurity,Hybrid,Yes,0,Startup,Cybersecurity Analyst
170,STU171,21,Male,PG,Mechanical,7.34,Intermediate,4.000000,66,Web Development,Hybrid,No,0,Startup,Software Engineer
171,STU172,26,Male,Diploma,Mechanical,9.89,Intermediate,9.000000,64,Data Science,Office,Yes,7,Startup,Data Analyst
172,STU173,26,Female,Diploma,Arts,9.32,Advanced,5.000000,79,Marketing,Office,Yes,3,Higher Study,Digital Marketing Specialist
173,STU174,21,Female,PG,Commerce,6.41,Advanced,5.308333,60,Finance,Office,No,8,Startup,Financial Analyst
174,STU175,22,Male,Diploma,Commerce,7.89,Intermediate,6.000000,89,Finance,Remote,No,0,Higher Study,Financial Analyst
175,STU176,23,Female,Diploma,Mechanical,8.79,Beginner,4.000000,92,Web Development,Hybrid,No,8,Startup,Software Engineer
176,STU177,20,Male,Diploma,Commerce,8.08,Beginner,1.000000,82,Finance,Hybrid,Yes,3,Job,Financial Analyst

In [19]:
df.to_csv('recommended_career_output.csv', index=False)
print("csv file saved successfully")

csv file saved successfully

In [20]:
df.shape

(243, 15)