# Employee Analysis Project

In [5]:
import pandas as pd 
import numpy as np

df = pd.read_csv('Extended_Employee_Performance_and_Productivity_Data.csv')
df

,Employee_ID,Department,Gender,Age,Job_Title,Hire_Date,Years_At_Company,Education_Level,Performance_Score,Monthly_Salary,Work_Hours_Per_Week,Projects_Handled,Overtime_Hours,Sick_Days,Remote_Work_Frequency,Team_Size,Training_Hours,Promotions,Employee_Satisfaction_Score,Resigned
0,1,IT,Male,55,Specialist,2022-01-19 08:03:05.556036,2,High School,5,6750.0,33,32,22,2,0,14,66,0,2.63,False
1,2,Finance,Male,29,Developer,2024-04-18 08:03:05.556036,0,High School,5,7500.0,34,34,13,14,100,12,61,2,1.72,False
2,3,Finance,Male,55,Specialist,2015-10-26 08:03:05.556036,8,High School,3,5850.0,37,27,6,3,50,10,1,0,3.17,False
3,4,Customer Support,Female,48,Analyst,2016-10-22 08:03:05.556036,7,Bachelor,2,4800.0,52,10,28,12,100,10,0,1,1.86,False
4,5,Engineering,Female,36,Analyst,2021-07-23 08:03:05.556036,3,Bachelor,2,4800.0,38,11,29,13,100,15,9,1,1.25,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,Finance,Male,27,Technician,2022-12-07 08:03:05.556036,1,Bachelor,4,4900.0,55,46,5,3,75,16,48,2,1.28,False
99996,99997,IT,Female,36,Consultant,2018-07-24 08:03:05.556036,6,Master,5,8250.0,39,35,7,0,0,10,77,1,3.48,True
99997,99998,Operations,Male,53,Analyst,2015-11-24 08:03:05.556036,8,High School,2,4800.0,31,13,6,5,0,5,87,1,2.60,False
99998,99999,HR,Female,22,Consultant,2015-08-03 08:03:05.556036,9,High School,5,8250.0,35,43,10,1,75,2,31,1,3.10,False
99999,100000,Finance,Female,43,Analyst,2024-03-04 08:03:05.556036,0,PhD,1,4400.0,51,43,27,11,75,13,45,1,2.64,False

In [11]:
np.random.seed(50)

In [14]:
df.isnull().sum()

Employee_ID                    0
Department                     0
Gender                         0
Age                            0
Job_Title                      0
Hire_Date                      0
Years_At_Company               0
Education_Level                0
Performance_Score              0
Monthly_Salary                 0
Work_Hours_Per_Week            0
Projects_Handled               0
Overtime_Hours                 0
Sick_Days                      0
Remote_Work_Frequency          0
Team_Size                      0
Training_Hours                 0
Promotions                     0
Employee_Satisfaction_Score    0
Resigned                       0
dtype: int64

In [25]:
Employee_ID  = np.arange(1,21)
print(Employee_ID)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

In [26]:
Age = np.random.randint(22,50,20)
print(Age)

[26 26 22 48 33 22 35 41 48 35 41 23 31 42 33 27 45 22 41 37]

In [31]:
department = np.random.choice(['HR', 'Finanace', 'IT', 'Sales'])
salary = np.random.randint(25000,80000,20)
exp = np.random.randint(1,15,20)
rating = np.round(np.random.uniform(1.0,5.0,20), 1)

In [36]:
df = pd.DataFrame({
    'Employee_ID' : Employee_ID ,
    'Age' : Age,
    'department' : department,
    'salary' : salary,
    'exp' : exp,
    'rating': rating
})

df

    Employee_ID  Age department  salary  exp  rating
0             1   26      Sales   59185   11     4.8
1             2   26      Sales   43363   14     3.9
2             3   22      Sales   35304    5     1.9
3             4   48      Sales   52706   14     4.5
4             5   33      Sales   27927    8     1.7
5             6   22      Sales   46498    1     2.4
6             7   35      Sales   31967   14     5.0
7             8   41      Sales   71320    7     1.4
8             9   48      Sales   65948    5     2.1
9            10   35      Sales   72258   12     3.0
10           11   41      Sales   66643    4     3.0
11           12   23      Sales   70733    1     4.1
12           13   31      Sales   27723    2     4.4
13           14   42      Sales   76458    4     3.3
14           15   33      Sales   46096   13     3.4
15           16   27      Sales   29582   12     3.4
16           17   45      Sales   76904    5     1.5
17           18   22      Sales   55203   10     4.8
18           19   41      Sales   52982   12     2.4
19           20   37      Sales   78812   13     1.6

# employee salary analysis

In [38]:
print(df.head())

   Employee_ID  Age department  salary  exp  rating
0            1   26      Sales   59185   11     4.8
1            2   26      Sales   43363   14     3.9
2            3   22      Sales   35304    5     1.9
3            4   48      Sales   52706   14     4.5
4            5   33      Sales   27927    8     1.7

In [39]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  20 non-null     int64
 1   Age          20 non-null     int32
 2   department   20 non-null     str
 3   salary       20 non-null     int32
 4   exp          20 non-null     int32
 5   rating       20 non-null     float64
dtypes: float64(1), int32(3), int64(1), str(1)
memory usage: 852.0 bytes
None

In [40]:
print(df.shape)

(20, 6)

In [41]:
print(df.size)

120

In [42]:
print(df.isnull().sum())

Employee_ID    0
Age            0
department     0
salary         0
exp            0
rating         0
dtype: int64

In [43]:
print(df.describe())

       Employee_ID        Age        salary        exp     rating
count     20.00000  20.000000     20.000000  20.000000  20.000000
mean      10.50000  33.900000  54380.600000   8.350000   3.130000
std        5.91608   8.813268  17654.698305   4.648429   1.213564
min        1.00000  22.000000  27723.000000   1.000000   1.400000
25%        5.75000  26.000000  41348.250000   4.750000   2.050000
50%       10.50000  34.000000  54092.500000   9.000000   3.150000
75%       15.25000  41.000000  70879.750000  12.250000   4.175000
max       20.00000  48.000000  78812.000000  14.000000   5.000000

In [44]:
print(df.tail())

    Employee_ID  Age department  salary  exp  rating
15           16   27      Sales   29582   12     3.4
16           17   45      Sales   76904    5     1.5
17           18   22      Sales   55203   10     4.8
18           19   41      Sales   52982   12     2.4
19           20   37      Sales   78812   13     1.6

In [48]:
# department wise average rating

print(df.groupby('department')['salary'].mean())

department
Sales    54380.6
Name: salary, dtype: float64

In [49]:
print(df.groupby('department')['rating'].max())

department
Sales    5.0
Name: rating, dtype: float64

In [50]:
print(df.groupby('department')['rating'].min())

department
Sales    1.4
Name: rating, dtype: float64

In [51]:
df[(df['salary'] > 35000) & (df['exp'] > 5)]

    Employee_ID  Age department  salary  exp  rating
0             1   26      Sales   59185   11     4.8
1             2   26      Sales   43363   14     3.9
3             4   48      Sales   52706   14     4.5
7             8   41      Sales   71320    7     1.4
9            10   35      Sales   72258   12     3.0
14           15   33      Sales   46096   13     3.4
17           18   22      Sales   55203   10     4.8
18           19   41      Sales   52982   12     2.4
19           20   37      Sales   78812   13     1.6

In [52]:
# low salary but high expaerience

df[(df['salary'] < 30000) & (df['exp'] > 10)]

    Employee_ID  Age department  salary  exp  rating
15           16   27      Sales   29582   12     3.4

In [53]:
df[(df['salary'] > 50000)]

    Employee_ID  Age department  salary  exp  rating
0             1   26      Sales   59185   11     4.8
3             4   48      Sales   52706   14     4.5
7             8   41      Sales   71320    7     1.4
8             9   48      Sales   65948    5     2.1
9            10   35      Sales   72258   12     3.0
10           11   41      Sales   66643    4     3.0
11           12   23      Sales   70733    1     4.1
13           14   42      Sales   76458    4     3.3
16           17   45      Sales   76904    5     1.5
17           18   22      Sales   55203   10     4.8
18           19   41      Sales   52982   12     2.4
19           20   37      Sales   78812   13     1.6

In [54]:
df[df['rating'] > 4]

    Employee_ID  Age department  salary  exp  rating
0             1   26      Sales   59185   11     4.8
3             4   48      Sales   52706   14     4.5
6             7   35      Sales   31967   14     5.0
11           12   23      Sales   70733    1     4.1
12           13   31      Sales   27723    2     4.4
17           18   22      Sales   55203   10     4.8

In [56]:
df[df['exp'] > 5]

    Employee_ID  Age department  salary  exp  rating
0             1   26      Sales   59185   11     4.8
1             2   26      Sales   43363   14     3.9
3             4   48      Sales   52706   14     4.5
4             5   33      Sales   27927    8     1.7
6             7   35      Sales   31967   14     5.0
7             8   41      Sales   71320    7     1.4
9            10   35      Sales   72258   12     3.0
14           15   33      Sales   46096   13     3.4
15           16   27      Sales   29582   12     3.4
17           18   22      Sales   55203   10     4.8
18           19   41      Sales   52982   12     2.4
19           20   37      Sales   78812   13     1.6

In [57]:
# age between 30  and 40

df[(df['Age'] > 30 ) & (df['Age'] < 40)]

    Employee_ID  Age department  salary  exp  rating
4             5   33      Sales   27927    8     1.7
6             7   35      Sales   31967   14     5.0
9            10   35      Sales   72258   12     3.0
12           13   31      Sales   27723    2     4.4
14           15   33      Sales   46096   13     3.4
19           20   37      Sales   78812   13     1.6